### ISSUE TITLE
Add hook options to the config to execute shell commands before/after generation.

### ISSUE THREAD

**Issue by Davenchy** [InioX/matugen#100]
I suggest adding an option to the TOML config file under the template section, such as `exec`, or perhaps splitting it into `pre_exec` and `post_exec`. This option would allow users to specify a shell command to be executed automatically.

- The `exec` option would run the specified command after the template generation is complete.
- Alternatively, the `pre_exec` option could run the command before generation, and the `post_exec` option could run it after generation.

I believe this approach would be more effective than implementing commands for each requested app individually. It would give users the flexibility to restart or perform any necessary actions before or after generating templates according to their needs.

---

I recall something similar might have been added before, possibly called `hook`, but it’s not mentioned in the documentation, so I’m unsure if it’s the same feature or something different.
I am talking about https://github.com/InioX/matugen/issues/83#issuecomment-2197180474

---

Anyway, Here’s an example using the `exec` approach:

```toml
[templates.swaync]
input_path = '~/.config/swaync/style-template.css'
output_path = '~/.config/swaync/style.css'
exec = 'swaync-client --reload-config && swaync-client --reload-css'
```

And here’s an example using the `{pre/post}_exec` approach:

```toml
[templates.some_app]
input_path = '~/.config/some_app/template.ext'
output_path = '~/.config/some_app/generated.ext'
pre_exec = 'echo "before generating" >> ~/logs'
post_exec = 'echo "after generating" >> ~/logs'
```

_Originally posted by @Davenchy in https://github.com/InioX/matugen/issues/94#issuecomment-2283292725_
