### ISSUE TITLE
How do I use matugen? I don't understand it.

### ISSUE THREAD

**Issue by F5T3** [InioX/matugen#118]
I have looked at the documentation and the [themes repo](https://github.com/InioX/matugen-themes), but still don't understand anything. I can't find anything externally and the examples folder didn't help me, because I don't know how to use it or "compile" the templates.

**Comment by ys5g** [comment]
Running `matugen image <image_path>` will "compile" all the templates configured in the `templates` section of `$HOME/.config/matugen/config.toml`.
You can do this to get started(assuming you use [swww](https://github.com/Horus645/swww) and it's in matugen's `$PATH`)
1. Write the following to that `config.toml` file
```toml
[config.wallpaper]
command = "swww"
arguments = ["img", "--transition-type", "center"]
set = true


[templates.waybar]
input_path = './templates/colors.css'
output_path = '~/.config/waybar/colors.css'
post_hook = 'pkill -SIGUSR2 waybar'
```
2. Copy [colors.css](https://github.com/iniox/matugen-themes/blob/main/templates/colors.css) to `$HOME/.config/matugen/templates/colors.css`
3. Add this line to the top of your ~/.config/waybar/style.css file
```css
@import "colors.css";
```
4. Run `matugen image <whatever_wallpaper_you_want>`
