### ISSUE TITLE
Template Example needs updates

### ISSUE THREAD

**Issue by Davido264** [InioX/matugen#77]
On the last update, `harmonized_colors` was reworked into `custom_colors`. So the new way to define `harmonized_colors` in templates is:
```TOML
# config
[config.custom_colors]
red = "#fb4934"
```
```
{{colors.red.default.hex}}
```

Where the previous way to define it was:
```TOML
# config
[config.colors_to_harmonize]
red = "#fb4934"
```
```
{{harmonized_colors.red.hex}}
```

However, the template example gave in `example/colors.whatever-extension`,  stills show the previous way to define templates. It should be updated to the new one

**Edit:** The config in `example/config.toml` is updated, the change is only required in  `example/colors.whatever-extension`,
