### ISSUE TITLE
Implement Blending

### ISSUE THREAD

**Issue by aurreland** [InioX/matugen#90]
I would like to know if it was possible to implement something to blend a certain color towards the colorscheme generated. For example it would allow to produce a base16 theme for the terminal   who is more related to the scheme instead of changing only background foreround and accent. So it would be like implementing the blend component to matugen. COuld be used like a filter idk...

**Comment by InioX** [comment]
```toml
[config.custom_colors]
red = { color = "#ff0000", blend = true }
```
